openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts Book
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Application for managing contacts
tags:
  - name: Contacts
    description: Operations with contacts
servers:
  - url: http://127.0.0.1:8081
paths:
  /waters/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /waters:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /waters/byDay:
    get:
      $ref: ../swagger/paths/water/by-day/get.yaml
  /waters/byMonth:
    get:
      $ref: ../swagger/paths/water/by-month/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
