openapi: 3.1.0
info:
  version: 1.0.0
  title: Aqua Track
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Application for managing contacts
tags:
  - name: Users
    description: Operations with Users
  - name: Auth
    description: Auth operations
servers:
  - url: http://127.0.0.1:8081
  - url: https://aqua-track-back.up.railway.app
paths:
  /users/{userId}:
    patch:
      $ref: ../swagger/paths/users/{userId}/patch.yaml
  /users/me:
    get:
      $ref: ../swagger/paths/users/me/get.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
  /auth/user-count:
    get:
      $ref: ../swagger/paths/auth/user-count/get.yaml
  /auth/get-oauth:
    get:
      $ref: ../swagger/paths/auth/get-oauth/get.yaml
  /auth/confirm-oauth:
    post:
      $ref: ../swagger/paths/auth/confirm-oauth/post.yaml
  /waters/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /waters:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /waters/byDay:
    get:
      $ref: ../swagger/paths/water/by-day/get.yaml
  /waters/byMonth:
    get:
      $ref: ../swagger/paths/water/by-month/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
